### PR TITLE
Add HERE iOS SDK examples on frontpage

### PR DESCRIPTION
**Pull request by freethan**
Update front page listing of available projects to reflect the inclusion of HERE iOS SDK examples.

### CODE REVIEW

**Comment by sschuberth** [comment]
FYI, here's a way to preview how the page would look like:

https://rawgit.com/heremaps/heremaps.github.io/b9d5097ae1b096c03aa44dc3c48e3772a7097099/index.html

Is it intentional that the new entry becomes the first one on the page?

**Comment by freethan** [comment]
Thanks for that :)
The order of projects is randomized on almost every run.

**Comment by sschuberth** [comment]
> The order of projects is randomized on almost every run.

How's that? I only see a simple forEach-loop [here](https://github.com/heremaps/heremaps.github.io/blob/b9d5097ae1b096c03aa44dc3c48e3772a7097099/index.html#L110).

**Comment by sschuberth** [comment]
Oh, and while at it, would you mind fixing the "HER" [typo](https://github.com/heremaps/heremaps.github.io/blob/b9d5097ae1b096c03aa44dc3c48e3772a7097099/index.html#L104) in another commit as part of this PR?

**Comment by freethan** [comment]
That's because the [https://github.com/heremaps/heremaps.github.io/blob/b9d5097ae1b096c03aa44dc3c48e3772a7097099/index.html#L123](ajax) call querying for the data gets triggered within that loop. Since it's asynchronous, not every call is guaranteed to return in order.

This certainly leaves room for improvement as I don't like this piece of code (running ajax requests in a loop...). We'd be better off managing things with promises.

**Comment by sschuberth** [comment]
Wait a second... if that `getJSON()` call is async, could it be that the wrong data is returned WRT what we've written to `$section` in the beginning of the loop?

**Comment by freethan** [comment]
It would seem so at first glance, but no, since $section is scoped within the anonymous function run on the forEach() statement.

$section gets declared and assigned anew each time forEach loops and it is within the scope of the callback of the ajax call. Each ajax call refers to that loop's version of $section.

As I said, I don't like it. It could be done inside the callback itself.

**Comment by sschuberth** [comment]
Thanks for the explanations! I believe this is good to merge then. Please do so.

**Pull request merged**
